Repository ITTA-DIV/Div-Backend, pull requests merged in 2024-01, with the labels that each got.

#23 feat #20: 이벤트 크롤링 자동화
  .github/workflows/gradle.yml
  SpringBoot-Damoacon/Dockerfile
  SpringBoot-Damoacon/crawling/eventus.py
  SpringBoot-Damoacon/requirements.txt
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/event/controller/EventController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/event/entity/Event.java
  SpringBoot-Damoacon/src/main/resources/application-dev.yml
Labels: ✨ feature, test, 🛠️ fix

#26 feat #12: 엔티티 수정
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/event/repository/CategoryRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/event/repository/EventRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/preference/repository/CommentRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/preference/repository/HeartRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/preference/repository/InterestRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/survey/repository/AnswerRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/survey/repository/SurveyRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/app/user/repository/UserRepository.java
Labels: ✨ feature, 🛠️ fix

#34 feat #13: 구글 소셜 로그인 구현
  SpringBoot-Damoacon/build.gradle
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/controller/MemberController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/GoogleLoginResponse.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/GoogleUserInformation.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/LoginResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/MemberResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/entity/Member.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/repository/MemberRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberServiceImpl.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/ContextUser.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/Role.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/TokenClaimVo.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Comment.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Heart.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Interest.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/user/repository/UserRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/common/ApiDataResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/common/ApiResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/config/SecurityConfig.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/constant/ErrorCode.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/exception/GeneralException.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/handler/ExceptionHandlerFilter.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/JwtUtil.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/ResponseUtil.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
  SpringBoot-Damoacon/src/main/resources/application.yml
Labels: ✨ feature, test, 🛠️ fix

#37 feat #13: JwtAuthenticationProcessingFilter를 통해 uri 검사하지 않도록 수정
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/config/SecurityConfig.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
Labels: 🛠️ fix

#39 feat #35: 이벤트 별 상세 조회 API
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/controller/EventController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/dto/DetailEventResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventServiceImpl.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/controller/MemberController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberServiceImpl.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/config/SecurityConfig.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/constant/ErrorCode.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/handler/ExceptionHandlerFilter.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
  SpringBoot-Damoacon/src/main/resources/application.yml
  SpringBoot-Damoacon/src/test/java/com/damoacon/domain/event/controller/EventControllerTest.java
Labels: feature, test

#38 Feature/33 검색 필터링 구현
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/controller/EventController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/dto/SearchRequestDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/dto/SearchResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/entity/Event.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/repository/EventRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventServiceImpl.java
  SpringBoot-Damoacon/src/test/java/com/damoacon/domain/event/controller/SearchTest.java
Labels: feature, test, 🛠️ fix

#40 fix: EventServiceImpl 변수 충돌 수정 (#33)
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventServiceImpl.java
Labels: 🛠️ fix

#41 Feat: 다른 브랜치에서 구현된 api 가져오기
  SpringBoot-Damoacon/build.gradle
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/controller/EventController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/dto/DetailEventResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/dto/SearchRequestDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/dto/SearchResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/entity/Event.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/repository/EventRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/event/service/EventServiceImpl.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/controller/MemberController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/GoogleLoginResponse.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/GoogleUserInformation.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/LoginResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/dto/MemberResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/entity/Member.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/repository/MemberRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberServiceImpl.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/ContextUser.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/Role.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/TokenClaimVo.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Comment.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Heart.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Interest.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/user/repository/UserRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/common/ApiDataResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/common/ApiResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/config/SecurityConfig.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/constant/ErrorCode.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/exception/GeneralException.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/handler/ExceptionHandlerFilter.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/JwtUtil.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/ResponseUtil.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
  SpringBoot-Damoacon/src/main/resources/application.yml
  SpringBoot-Damoacon/src/test/java/com/damoacon/domain/event/controller/EventControllerTest.java
  SpringBoot-Damoacon/src/test/java/com/damoacon/domain/event/controller/SearchTest.java
Labels: enhancement

#49 fix #13: JwtProcessingAuthenticationFilter에서 uri 예외처리하도록 수정
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/member/service/MemberService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/config/SecurityConfig.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/JwtUtil.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
Labels: 🛠️ fix

#50 feat #36: 이벤트 별 댓글 API
  SpringBoot-Damoacon/src/main/java/com/damoacon/Application.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/model/BaseTimeEntity.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/controller/CommentController.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/dto/comment/CommentRequestDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/dto/comment/CommentResponseDto.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/entity/Comment.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/repository/CommentRepository.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/service/CommentService.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/domain/preference/service/CommentServiceImpl.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/config/SecurityConfig.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/constant/ErrorCode.java
  SpringBoot-Damoacon/src/test/java/com/damoacon/domain/preference/controller/CommentControllerTest.java
Labels: feature, test, 🛠️ fix

#51 fix #13: JWT 관련 로직 전체적으로 정리
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/JwtUtil.java
  SpringBoot-Damoacon/src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
Labels: enhancement, 🛠️ fix, ♻️ refactor

#59 feat #53: EC2에 도메인과 HTTPS 적용
  .github/workflows/gradle.yml
  Dockerfile-nginx
  docker-compose.yml
  nginx/conf.d/nginx.conf
  settings.gradle
  src/main/java/com/damoacon/global/config/SecurityConfig.java
Labels: feature, 🛠️ fix

#62 feat #53: nginx 재시작과 ssl 인증서 갱신 자동화 추가
  docker-compose.yml
Labels: feature

#61 feat #57: 예외처리, 불필요한 print문 제거
  crawling/eventus.py
Labels: feature

#65 refactor #60: 관리자, 좋아요, 관심분야 관련 코드 전체적으로 정리
  src/main/java/com/damoacon/domain/manager/controller/ManagerController.java
  src/main/java/com/damoacon/domain/manager/service/ManagerServiceImpl.java
  src/main/java/com/damoacon/domain/preference/controller/HeartController.java
  src/main/java/com/damoacon/domain/preference/controller/InterestController.java
  src/main/java/com/damoacon/domain/preference/dto/heart/EventSimpleDto.java
  src/main/java/com/damoacon/domain/preference/dto/heart/HeartDto.java
  src/main/java/com/damoacon/domain/preference/dto/heart/HeartSimpleDto.java
  src/main/java/com/damoacon/domain/preference/dto/heart/MemberSimpleDto.java
  src/main/java/com/damoacon/domain/preference/dto/interest/InterestDto.java
  src/main/java/com/damoacon/domain/preference/dto/interest/InterestSimpleDto.java
  src/main/java/com/damoacon/domain/preference/dto/interest/MyPageDto.java
  src/main/java/com/damoacon/domain/preference/service/HeartService.java
  src/main/java/com/damoacon/domain/preference/service/HeartServiceImpl.java
  src/main/java/com/damoacon/domain/preference/service/InterestService.java
  src/main/java/com/damoacon/domain/preference/service/InterestServiceImpl.java
Labels: ♻️ refactor

#66 feat #63: manager 제외하고 정리
  src/main/java/com/damoacon/domain/event/controller/EventController.java
  src/main/java/com/damoacon/domain/event/dto/SearchRequestDto.java
  src/main/java/com/damoacon/domain/event/dto/SearchResponseDto.java
  src/main/java/com/damoacon/domain/event/entity/Event.java
  src/main/java/com/damoacon/domain/event/repository/EventRepository.java
  src/main/java/com/damoacon/domain/event/service/EventService.java
  src/main/java/com/damoacon/domain/event/service/EventServiceImpl.java
  src/main/java/com/damoacon/domain/manager/controller/ManagerController.java
  src/main/java/com/damoacon/domain/member/controller/MemberController.java
  src/main/java/com/damoacon/domain/member/dto/EventSimpleDto.java
  src/main/java/com/damoacon/domain/member/dto/MemberResponseDto.java
  src/main/java/com/damoacon/domain/member/dto/MemberSimpleDto.java
  src/main/java/com/damoacon/domain/member/dto/MyPageDto.java
  src/main/java/com/damoacon/domain/member/entity/Member.java
  src/main/java/com/damoacon/domain/member/service/MemberService.java
  src/main/java/com/damoacon/domain/member/service/MemberServiceImpl.java
  src/main/java/com/damoacon/domain/model/Role.java
  src/main/java/com/damoacon/domain/preference/controller/CommentController.java
  src/main/java/com/damoacon/domain/preference/controller/HeartController.java
  src/main/java/com/damoacon/domain/preference/controller/InterestController.java
  src/main/java/com/damoacon/domain/preference/dto/heart/HeartDto.java
  src/main/java/com/damoacon/domain/preference/dto/heart/HeartSimpleDto.java
  src/main/java/com/damoacon/domain/preference/dto/interest/InterestDto.java
  src/main/java/com/damoacon/domain/preference/repository/HeartRepository.java
  src/main/java/com/damoacon/domain/preference/repository/InterestRepository.java
  src/main/java/com/damoacon/domain/preference/service/CommentService.java
  src/main/java/com/damoacon/domain/preference/service/CommentServiceImpl.java
  src/main/java/com/damoacon/domain/preference/service/HeartService.java
  src/main/java/com/damoacon/domain/preference/service/HeartServiceImpl.java
  src/main/java/com/damoacon/domain/preference/service/InterestService.java
  src/main/java/com/damoacon/domain/preference/service/InterestServiceImpl.java
  src/main/java/com/damoacon/domain/survey/entity/Answer.java
  src/main/java/com/damoacon/domain/survey/entity/Survey.java
  src/main/java/com/damoacon/domain/survey/repository/AnswerRepository.java
  src/main/java/com/damoacon/domain/survey/repository/SurveyRepository.java
  src/main/java/com/damoacon/global/config/SecurityConfig.java
  src/main/java/com/damoacon/global/config/WebConfig.java
  src/main/java/com/damoacon/global/constant/ErrorCode.java
  src/test/java/com/damoacon/domain/event/service/EventServiceTest.java
Labels: feature, ♻️ refactor

#67 refactor #63: Manager, CI/CD 배포 전 코드 정리
  .github/workflows/gradle.yml
  .gitignore
  src/main/java/com/damoacon/domain/manager/controller/ManagerController.java
  src/main/java/com/damoacon/domain/manager/dto/EventCreateDto.java
  src/main/java/com/damoacon/domain/manager/dto/EventResponseDto.java
  src/main/java/com/damoacon/domain/manager/dto/ManagerCheckDto.java
  src/main/java/com/damoacon/domain/manager/repository/EventManagerRepository.java
  src/main/java/com/damoacon/domain/manager/service/ManagerService.java
  src/main/java/com/damoacon/domain/manager/service/ManagerServiceImpl.java
  src/main/java/com/damoacon/global/config/SecurityConfig.java
  src/main/java/com/damoacon/global/constant/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/keystore.p12
Labels: ♻️ refactor

#71 fix: MemberController에서 refreshToken요청 처리
  src/main/java/com/damoacon/domain/member/controller/MemberController.java
  src/main/java/com/damoacon/domain/member/service/MemberService.java
  src/main/java/com/damoacon/domain/member/service/MemberServiceImpl.java
  src/main/java/com/damoacon/global/config/SecurityConfig.java
  src/main/java/com/damoacon/global/util/filter/JwtAuthenticationProcessingFilter.java
Labels: 🛠️ fix
